import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { api } from "~/utils/api";

export default function Home() {
  const [selected, setSelected] = useState<string[]>([]);
  const [mistakes, setMistakes] = useState<number>(3);

  const words = [
    "canary",
    "Irate",
    "lost",
    "school bus",
    "beach",
    "gull",
    "furious",
    "booby",
    "banana",
    "beastie",
    "sunflower",
    "livid",
    "hardy",
    "pelican",
    "incensed",
    "puffin",
  ];

  const handleSelection = (word: string) => {
    // if the word is already selected, remove it from the array and max selected words is 4
    if (selected.includes(word)) {
      setSelected(selected.filter((item) => item !== word));
    } else if (selected.length < 4) {
      // if the word is not selected, add it to the array
      setSelected([...selected, word]);
    }
  };

  return (
    <>
      <Head>
        <title>Custom Connections</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <div className="flex flex-col items-center justify-center">
          <h1 className="text-center text-4xl font-bold">
            Custom Connections Game
          </h1>
          {/* description of the website */}
          <p className="text-center text-xl">
            Based on the connections game. Create your own game and share it.
          </p>
          {/* create button that links to the create link */}
          <button className="mt-5 rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700">
            <Link href="/create">Create a game</Link>
          </button>

          {/* by me */}
          <p className="mt-5 italic text-gray-500">by Enrico Simon</p>
        </div>
      </main>
    </>
  );
}
