import Head from "next/head";
import React from "react";

function index() {
  return (
    <>
      <Head>
        <title>Custom Connections</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        {/* div to center and put title on top of the page */}
        <div className="flex flex-col items-center justify-center">
          <h1 className="text-6xl font-bold">Custom Connections Game</h1>
          {/* 4 by 4 grid in the middle of the screen */}
          <div className="mt-3 grid grid-cols-5 gap-4">
            <div
              className={`col-span-1  rounded-lg bg-yellow-300 p-4 shadow-lg`}
            >
              <div className="flex flex-col items-center justify-center p-4 px-6 ">
                <p className="text-xl font-bold uppercase ">Easy</p>
              </div>
            </div>
            {/* EASY WORDS */}
            {
              //   loop 4 times
              Array.from(Array(4).keys()).map((i) => (
                //add the card id to the selected array
                <div
                  key={i}
                  //if the card id is in the selected array, add the selected class
                  className={`flex  rounded-lg p-4 shadow-lg`}
                >
                  <div className="flex flex-col items-center justify-center p-4 px-3 ">
                    {/* input easy words */}
                    <input
                      className="bg-transparent p-1 text-center text-base font-bold uppercase"
                      placeholder="Input easy words"
                    />
                  </div>
                </div>
              ))
            }
            {/* MEDIUM WORDS */}
            <div
              className={`col-span-1  rounded-lg bg-green-500 p-4 shadow-lg`}
            >
              <div className="flex flex-col items-center justify-center p-4 px-6 ">
                <p className="text-xl font-bold uppercase">Medium</p>
              </div>
            </div>
            {
              //   loop 4 times
              Array.from(Array(4).keys()).map((i) => (
                //add the card id to the selected array
                <div
                  key={i}
                  //if the card id is in the selected array, add the selected class
                  className={`flex rounded-lg  p-2 shadow-lg`}
                >
                  <div className="flex flex-col items-center justify-center  p-4 px-3">
                    {/* input easy words */}
                    <input
                      className="bg-transparent p-1 text-center text-base font-bold uppercase"
                      placeholder="Input Medium words"
                    />
                  </div>
                </div>
              ))
            }
            {/* HARD WORDS */}

            <div
              className={`col-span-1  rounded-lg  bg-blue-500 p-4 shadow-lg`}
            >
              <div className="flex flex-col items-center justify-center p-4 px-6 ">
                <p className="text-xl font-bold uppercase">Hard</p>
              </div>
            </div>
            {
              //   loop 4 times
              Array.from(Array(4).keys()).map((i) => (
                //add the card id to the selected array
                <div
                  key={i}
                  //if the card id is in the selected array, add the selected class
                  className={`flex  rounded-lg p-2 shadow-lg`}
                >
                  <div className="flex flex-col items-center justify-center p-4 px-3 ">
                    {/* input easy words */}
                    <input
                      className="bg-transparent p-1 text-center text-base font-bold uppercase"
                      placeholder="Input Hard words"
                    />
                  </div>
                </div>
              ))
            }
            {/* Super Hard Words */}
            <div
              className={`col-span-1  rounded-lg bg-purple-600 p-4 shadow-lg`}
            >
              <div className="flex flex-col items-center justify-center p-4 px-6 ">
                <p className="text-xl font-bold uppercase">Tricky</p>
              </div>
            </div>
            {
              //   loop 4 times
              Array.from(Array(4).keys()).map((i) => (
                //add the card id to the selected array
                <div
                  key={i}
                  //if the card id is in the selected array, add the selected class
                  className={`flex  rounded-lg p-2 shadow-lg`}
                >
                  <div className="flex flex-col items-center justify-center p-4 px-3 ">
                    {/* input easy words */}
                    <input
                      className="bg-transparent p-1 text-center  text-base font-bold uppercase"
                      placeholder="Input Tricky words"
                    />
                  </div>
                </div>
              ))
            }
            <div className="col-span-5 flex items-center justify-center">
              <button className="  rounded-full bg-gray-900 p-2 px-4 text-white ">
                <p className="text-xl">Submit</p>
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default index;
